# Generated by Django 5.2 on 2025-04-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('IT', 'IT'), ('Infrastructure', 'Infrastructure'), ('Electrical', 'Electrical'), ('House keeping', 'House keeping')], max_length=100, null=True),
        ),
    ]
