# Generated by Django 5.2 on 2025-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
